# GoReleaser configuration for CCM
# https://goreleaser.com/

version: 2

project_name: ccm

before:
  hooks:
    - go mod tidy

builds:
  - id: ccm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X ccm/internal/version.Version={{.Version}}
      - -X ccm/internal/version.Commit={{.Commit}}
      - -X ccm/internal/version.Date={{.Date}}
    binary: ccm

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\(.+\))?!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch

release:
  github:
    owner: taliove
    name: go-claude-model
  draft: false
  prerelease: auto
  header: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install taliove/tap/ccm
    ```

    ### Quick Install (Linux/macOS)
    ```bash
    curl -fsSL https://raw.githubusercontent.com/taliove/go-claude-model/main/scripts/install.sh | bash
    ```

    ### Manual Download
    Download the appropriate binary for your platform from the assets below.

brews:
  - repository:
      owner: taliove
      name: go-claude-model
      branch: main
    directory: Formula
    homepage: "https://github.com/taliove/go-claude-model"
    description: "Claude Code Manager - Manage multiple AI model providers"
    license: "MIT"
    install: |
      bin.install "ccm"
    test: |
      system "#{bin}/ccm", "--version"
