# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccm < Formula
  desc "Claude Code Manager - Manage multiple AI model providers"
  homepage "https://github.com/taliove/go-claude-model"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taliove/go-claude-model/releases/download/v0.4.0/ccm_0.4.0_darwin_amd64.tar.gz"
      sha256 "4b00f61309ab182678ab9bc866c2bce16ed1526606d03a550a701e5b21f57620"

      def install
        bin.install "ccm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/taliove/go-claude-model/releases/download/v0.4.0/ccm_0.4.0_darwin_arm64.tar.gz"
      sha256 "be8c6bc91879837182eefa87fd487196c6c4f97eec11543122f76f4d01590925"

      def install
        bin.install "ccm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/taliove/go-claude-model/releases/download/v0.4.0/ccm_0.4.0_linux_amd64.tar.gz"
      sha256 "25a4282d7a747e38d3f5691bd89502d0774eabb49fb3162393ca5ae1f1cd7889"
      def install
        bin.install "ccm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taliove/go-claude-model/releases/download/v0.4.0/ccm_0.4.0_linux_arm64.tar.gz"
      sha256 "7507f729e630d80985d286367ef1dbaa58e964a3c6bbda409c2ba4efa8991bed"
      def install
        bin.install "ccm"
      end
    end
  end

  test do
    system "#{bin}/ccm", "--version"
  end
end
