#!/bin/bash
#
# release.sh - CCM Release Script
#
# Usage: ./release.sh <version>
# Example: ./release.sh 0.2.0
#
# This script:
# 1. Updates version in Makefile
# 2. Builds all platform binaries
# 3. Calculates checksums
# 4. Creates git tag
# 5. Pushes to remote
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check arguments
if [ -z "$1" ]; then
    log_error "Usage: $0 <version>"
    echo ""
    echo "Example: $0 0.2.0"
    echo ""
    echo "Version format: MAJOR.MINOR.PATCH"
    echo "  - MAJOR: Breaking changes"
    echo "  - MINOR: New features (backward compatible)"
    echo "  - PATCH: Bug fixes"
    exit 1
fi

VERSION=$1

# Validate version format (semver)
SEMVER_REGEX='^[0-9]+\.[0-9]+\.[0-9]+$'
if ! echo "$VERSION" | grep -qE "$SEMVER_REGEX"; then
    log_error "Invalid version format: $VERSION"
    echo "Expected format: MAJOR.MINOR.PATCH (e.g., 0.2.0)"
    exit 1
fi

log_info "🚀 Starting CCM v$VERSION release process"
echo ""

# Step 1: Check git status
log_info "Step 1: Checking git status..."
if [ -n "$(git status --porcelain)" ]; then
    log_warn "You have uncommitted changes:"
    git status --short
    echo ""
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_error "Aborted"
        exit 1
    fi
fi

# Step 2: Update version in Makefile
log_info "Step 2: Updating version to $VERSION..."
CURRENT_VERSION=$(grep "^VERSION :=" Makefile | cut -d'=' -f2 | tr -d ' ')
log_info "Current version: $CURRENT_VERSION -> $VERSION"

# Update VERSION in Makefile
sed -i "s/^VERSION := .*/VERSION := $VERSION/" Makefile
log_success "Version updated in Makefile"

# Step 3: Build all platforms
log_info "Step 3: Building all platforms..."
make release-all
log_success "All platforms built"

# Step 4: Calculate checksums
log_info "Step 4: Calculating checksums..."
make checksum
log_success "Checksums calculated"

# Step 5: Stage changes
log_info "Step 5: Staging changes..."
git add -A

# Step 6: Create commit
log_info "Step 6: Creating commit..."
COMMIT_MSG="Release v$VERSION

Changes:
- Version bump to v$VERSION
- Built binaries for linux/darwin (amd64/arm64)
- Added checksums.txt

Generated by release.sh"
git commit -m "$COMMIT_MSG"
log_success "Commit created: $(git rev-parse --short HEAD)"

# Step 7: Create tag
log_info "Step 7: Creating tag v$VERSION..."
git tag -a "v$VERSION" -m "Release v$VERSION"
log_success "Tag created: v$VERSION"

echo ""
echo "========================================"
log_success "Release v$VERSION prepared successfully!"
echo "========================================"
echo ""
echo "📦 Artifacts created:"
ls -lh ccm-* checksums.txt 2>/dev/null | tail -n +2
echo ""
echo "📝 Next steps:"
echo "   1. Review the commit: git log --oneline -1"
echo "   2. Push to remote: git push origin main && git push origin v$VERSION"
echo "   3. Create GitHub Release: https://github.com/taliove/go-claude-model/releases/new?tag=v$VERSION"
echo "   4. Upload files: ccm-*, checksums.txt"
echo ""
read -p "Push to remote now? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Pushing to remote..."
    git push origin main
    git push origin "v$VERSION"
    log_success "Pushed to remote!"
    echo ""
    echo "🎉 Go create your GitHub release:"
    echo "   https://github.com/taliove/go-claude-model/releases/new?tag=v$VERSION"
fi
